using System;
using System.Collections.Generic;
using System.Data;
using Microsoft.Data.SqlClient;
using HealthClinicApp.Entity;
using HealthClinicApp.Interface;

namespace HealthClinicApp.Service
{
    public class VisitHistoryService : IVisitHistoryService
    {
        private readonly DBConnectionUtility _dbUtility;

        public VisitHistoryService(DBConnectionUtility dbUtility)
        {
            _dbUtility = dbUtility;
        }

        private SqlConnection GetConnection() => _dbUtility.CreateConnection();

        // Retrieve full visit history for a specific patient
        public List<VisitHistory> GetPatientVisitHistory(int patientId)
        {
            var list = new List<VisitHistory>();
            using var conn = GetConnection();
            using var cmd = new SqlCommand("sp_GetPatientVisitHistory", conn)
            {
                CommandType = CommandType.StoredProcedure
            };
            cmd.Parameters.AddWithValue("@PatientID", patientId);

            conn.Open();
            using var reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                list.Add(new VisitHistory
                {
                    AppointmentID = Convert.ToInt32(reader["AppointmentID"]),
                    AppointmentDate = Convert.ToDateTime(reader["AppointmentDate"]),
                    DoctorName = reader["DoctorName"].ToString() ?? "",
                    Specialization = reader["Specialization"].ToString() ?? "",
                    Status = reader["Status"].ToString() ?? "",
                    BillID = reader["BillID"] != DBNull.Value ? Convert.ToInt32(reader["BillID"]) : null,
                    TotalAmount = reader["TotalAmount"] != DBNull.Value ? Convert.ToDecimal(reader["TotalAmount"]) : null,
                    PaymentStatus = reader["PaymentStatus"] != DBNull.Value ? reader["PaymentStatus"].ToString() : null
                });
            }
            return list;
        }

        // Get audit log entries generated by Patient triggers
        // Disconnected Architecture: SqlDataAdapter.Fill() auto-opens and closes connection
        public DataTable GetPatientAuditLogs()
        {
            var dt = new DataTable();
            using var conn = GetConnection();
            using var cmd = new SqlCommand("SELECT TOP 20 * FROM PatientAudit ORDER BY ActionDate DESC", conn);
            using var adapter = new SqlDataAdapter(cmd);
            adapter.Fill(dt); // Fill() internally opens connection, loads data into DataTable, then closes connection
            return dt;
        }

        // Get audit log entries generated by Appointment triggers
        // Disconnected Architecture: SqlDataAdapter.Fill() auto-opens and closes connection
        public DataTable GetAppointmentAuditLogs()
        {
            var dt = new DataTable();
            using var conn = GetConnection();
            using var cmd = new SqlCommand("SELECT TOP 20 * FROM AppointmentAudit ORDER BY ActionDate DESC", conn);
            using var adapter = new SqlDataAdapter(cmd);
            adapter.Fill(dt); // Fill() internally opens connection, loads data into DataTable, then closes connection
            return dt;
        }
    }
}
